version: '3.8'

services:
  django_gunicorn:
    container_name: django_gunicorn
    volumes:
      - static:/static
      - ./django_project:/app
    env_file:
      - .env
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx_django
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 8008:80
    depends_on:
      - django_gunicorn

volumes:
  static:
