--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.2 (Debian 16.2-1.pgdg120+2)

-- SET statement_timeout = 0;
-- SET lock_timeout = 0;
-- SET idle_in_transaction_session_timeout = 0;
-- SET client_encoding = 'UTF8';
-- SET standard_conforming_strings = on;
-- SELECT pg_catalog.set_config('search_path', '', false);
-- SET check_function_bodies = false;
-- SET xmloption = content;
-- SET client_min_messages = warning;
-- SET row_security = off;

-- SET default_tablespace = '';

-- SET default_table_access_method = heap;

-- --
-- -- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.auth_group (
--     id integer NOT NULL,
--     name character varying(150) NOT NULL
-- );


-- ALTER TABLE public.auth_group OWNER TO postgres;

-- --
-- -- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.auth_group_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.auth_group_permissions (
--     id integer NOT NULL,
--     group_id integer NOT NULL,
--     permission_id integer NOT NULL
-- );


-- ALTER TABLE public.auth_group_permissions OWNER TO postgres;

-- --
-- -- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.auth_group_permissions_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.auth_permission (
--     id integer NOT NULL,
--     name character varying(255) NOT NULL,
--     content_type_id integer NOT NULL,
--     codename character varying(100) NOT NULL
-- );


-- ALTER TABLE public.auth_permission OWNER TO postgres;

-- --
-- -- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.auth_permission_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.auth_user (
--     id integer NOT NULL,
--     password character varying(128) NOT NULL,
--     last_login timestamp with time zone,
--     is_superuser boolean NOT NULL,
--     username character varying(150) NOT NULL,
--     first_name character varying(150) NOT NULL,
--     last_name character varying(150) NOT NULL,
--     email character varying(254) NOT NULL,
--     is_staff boolean NOT NULL,
--     is_active boolean NOT NULL,
--     date_joined timestamp with time zone NOT NULL
-- );


-- ALTER TABLE public.auth_user OWNER TO postgres;

-- --
-- -- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.auth_user_groups (
--     id integer NOT NULL,
--     user_id integer NOT NULL,
--     group_id integer NOT NULL
-- );


-- ALTER TABLE public.auth_user_groups OWNER TO postgres;

-- --
-- -- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.auth_user_groups_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.auth_user_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.auth_user_user_permissions (
--     id integer NOT NULL,
--     user_id integer NOT NULL,
--     permission_id integer NOT NULL
-- );


-- ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

-- --
-- -- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.auth_user_user_permissions_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


--
-- Name: andamento; Type: TABLE; Schema: public; Owner: postgres
--

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE public.andamento (
    id bigint NOT NULL,
    porcent_executada integer NOT NULL,
    data date NOT NULL,
    atividade_id bigint NOT NULL
);


ALTER TABLE public.andamento OWNER TO postgres;

--
-- Name: andamento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.andamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.andamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: atividade; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.atividade (
    id bigint NOT NULL,
    nome character varying(2000) NOT NULL,
    descricao text,
    link_img character varying(4000),
    link_exec character varying(4000),
    peso integer,
    data_inicio date NOT NULL,
    data_final date NOT NULL,
    fp_nit_id bigint,
    meta_id bigint,
    CONSTRAINT check_activity_fields CHECK ((((meta_id IS NOT NULL) AND (fp_nit_id IS NULL)) OR ((meta_id IS NULL) AND (fp_nit_id IS NOT NULL))))
);


ALTER TABLE public.atividade OWNER TO postgres;

--
-- Name: atividade_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.atividade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.atividade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cargo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cargo (
    id bigint NOT NULL,
    nome character varying(2000) NOT NULL,
    descricao text
);


ALTER TABLE public.cargo OWNER TO postgres;

--
-- Name: cargo_empregado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cargo_empregado (
    id bigint NOT NULL,
    data_inicio_cargo date NOT NULL,
    data_final_cargo date,
    cargo_id bigint NOT NULL,
    empregado_id bigint NOT NULL
);


ALTER TABLE public.cargo_empregado OWNER TO postgres;

--
-- Name: cargo_empregado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cargo_empregado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cargo_empregado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cargo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cargo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cargo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contrato; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contrato (
    id bigint NOT NULL,
    data_contratacao date NOT NULL,
    data_vencimento date NOT NULL,
    cargo_empregado_atual_id bigint NOT NULL,
    empregado_id bigint NOT NULL
);


ALTER TABLE public.contrato OWNER TO postgres;

--
-- Name: contrato_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contrato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contrato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: convenio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.convenio (
    id bigint NOT NULL,
    codigo character varying(255) NOT NULL,
    nome character varying(2000) NOT NULL,
    descricao text,
    data_inicio date NOT NULL,
    data_final date NOT NULL,
    orcamento double precision NOT NULL
);


ALTER TABLE public.convenio OWNER TO postgres;

--
-- Name: convenio_empregado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.convenio_empregado (
    id bigint NOT NULL,
    atuacao_empregado character varying(255) NOT NULL,
    data_inicio_atuacao date NOT NULL,
    data_final_atuacao date NOT NULL,
    convenio_id bigint NOT NULL,
    empregado_id bigint NOT NULL
);


ALTER TABLE public.convenio_empregado OWNER TO postgres;

--
-- Name: convenio_empregado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.convenio_empregado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.convenio_empregado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: convenio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.convenio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.convenio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empregado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empregado (
    id bigint NOT NULL,
    matricula_cracha character varying(255) NOT NULL,
    nome character varying(2000) NOT NULL,
    cpf character varying(15) NOT NULL,
    email character varying(255),
    data_nascimento date NOT NULL,
    genero character varying(255) NOT NULL,
    telefone character varying(255),
    graduacao character varying(255) NOT NULL
);


ALTER TABLE public.empregado OWNER TO postgres;

--
-- Name: empregado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empregado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empregado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evento (
    id bigint NOT NULL,
    nome character varying(2000) NOT NULL,
    descricao text,
    denominacao character varying(2000) NOT NULL,
    participantes character varying(2000) NOT NULL,
    categoria_participantes character varying(2000) NOT NULL,
    data_inicio date NOT NULL,
    data_final date NOT NULL,
    convenio_id bigint NOT NULL
);


ALTER TABLE public.evento OWNER TO postgres;

--
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exec_financeira; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exec_financeira (
    id bigint NOT NULL,
    orc_total double precision,
    rep_recebidos double precision,
    saldo_receber double precision,
    redimento double precision,
    total_realizado double precision,
    total_empenhado double precision,
    saldo_executar double precision,
    data date,
    convenio_id bigint NOT NULL
);


ALTER TABLE public.exec_financeira OWNER TO postgres;

--
-- Name: exec_financeira_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exec_financeira ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exec_financeira_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exec_valores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exec_valores (
    id bigint NOT NULL,
    desc_execute text,
    aloc character varying(50),
    custo double precision,
    rubrica character varying(255),
    data date,
    convenio_id bigint NOT NULL,
    meta character varying(255) NOT NULL
);


ALTER TABLE public.exec_valores OWNER TO postgres;

--
-- Name: exec_valores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exec_valores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exec_valores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fp_nit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fp_nit (
    id bigint NOT NULL,
    nome character varying(2000) NOT NULL,
    descricao text,
    data_inicio date NOT NULL,
    data_final date NOT NULL,
    meta_id bigint NOT NULL
);


ALTER TABLE public.fp_nit OWNER TO postgres;

--
-- Name: fp_nit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fp_nit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fp_nit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meta (
    id bigint NOT NULL,
    nome character varying(2000) NOT NULL,
    descricao text,
    data_inicio date NOT NULL,
    data_final date NOT NULL,
    convenio_id bigint NOT NULL
);


ALTER TABLE public.meta OWNER TO postgres;

--
-- Name: meta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

-- CREATE TABLE public.django_admin_log (
--     id integer NOT NULL,
--     action_time timestamp with time zone NOT NULL,
--     object_id text,
--     object_repr character varying(200) NOT NULL,
--     action_flag smallint NOT NULL,
--     change_message text NOT NULL,
--     content_type_id integer,
--     user_id integer NOT NULL,
--     CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
-- );


-- ALTER TABLE public.django_admin_log OWNER TO postgres;

-- --
-- -- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.django_admin_log_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.django_content_type (
--     id integer NOT NULL,
--     app_label character varying(100) NOT NULL,
--     model character varying(100) NOT NULL
-- );


-- ALTER TABLE public.django_content_type OWNER TO postgres;

-- --
-- -- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.django_content_type_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.django_migrations (
--     id integer NOT NULL,
--     app character varying(255) NOT NULL,
--     name character varying(255) NOT NULL,
--     applied timestamp with time zone NOT NULL
-- );


-- ALTER TABLE public.django_migrations OWNER TO postgres;

-- --
-- -- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
-- --

-- ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
--     SEQUENCE NAME public.django_migrations_id_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1
-- );


-- --
-- -- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
-- --

-- CREATE TABLE public.django_session (
--     session_key character varying(40) NOT NULL,
--     session_data text NOT NULL,
--     expire_date timestamp with time zone NOT NULL
-- );


-- ALTER TABLE public.django_session OWNER TO postgres;

-- --
-- -- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.auth_group (id, name) FROM stdin;
-- \.


-- --
-- -- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
-- 1	Can add log entry	1	add_logentry
-- 2	Can change log entry	1	change_logentry
-- 3	Can delete log entry	1	delete_logentry
-- 4	Can view log entry	1	view_logentry
-- 5	Can add permission	2	add_permission
-- 6	Can change permission	2	change_permission
-- 7	Can delete permission	2	delete_permission
-- 8	Can view permission	2	view_permission
-- 9	Can add group	3	add_group
-- 10	Can change group	3	change_group
-- 11	Can delete group	3	delete_group
-- 12	Can view group	3	view_group
-- 13	Can add user	4	add_user
-- 14	Can change user	4	change_user
-- 15	Can delete user	4	delete_user
-- 16	Can view user	4	view_user
-- 17	Can add content type	5	add_contenttype
-- 18	Can change content type	5	change_contenttype
-- 19	Can delete content type	5	delete_contenttype
-- 20	Can view content type	5	view_contenttype
-- 21	Can add session	6	add_session
-- 22	Can change session	6	change_session
-- 23	Can delete session	6	delete_session
-- 24	Can view session	6	view_session
-- 25	Can add cargo	7	add_cargo
-- 26	Can change cargo	7	change_cargo
-- 27	Can delete cargo	7	delete_cargo
-- 28	Can view cargo	7	view_cargo
-- 29	Can add convenio	8	add_convenio
-- 30	Can change convenio	8	change_convenio
-- 31	Can delete convenio	8	delete_convenio
-- 32	Can view convenio	8	view_convenio
-- 33	Can add empregado	9	add_empregado
-- 34	Can change empregado	9	change_empregado
-- 35	Can delete empregado	9	delete_empregado
-- 36	Can view empregado	9	view_empregado
-- 37	Can add contrato	10	add_contrato
-- 38	Can change contrato	10	change_contrato
-- 39	Can delete contrato	10	delete_contrato
-- 40	Can view contrato	10	view_contrato
-- 41	Can add meta	11	add_meta
-- 42	Can change meta	11	change_meta
-- 43	Can delete meta	11	delete_meta
-- 44	Can view meta	11	view_meta
-- 45	Can add atividade	12	add_atividade
-- 46	Can change atividade	12	change_atividade
-- 47	Can delete atividade	12	delete_atividade
-- 48	Can view atividade	12	view_atividade
-- 49	Can add evento	13	add_evento
-- 50	Can change evento	13	change_evento
-- 51	Can delete evento	13	delete_evento
-- 52	Can view evento	13	view_evento
-- 53	Can add convenio_ empregado	14	add_convenio_empregado
-- 54	Can change convenio_ empregado	14	change_convenio_empregado
-- 55	Can delete convenio_ empregado	14	delete_convenio_empregado
-- 56	Can view convenio_ empregado	14	view_convenio_empregado
-- 57	Can add andamento	15	add_andamento
-- 58	Can change andamento	15	change_andamento
-- 59	Can delete andamento	15	delete_andamento
-- 60	Can view andamento	15	view_andamento
-- 61	Can add cargo_ empregado	16	add_cargo_empregado
-- 62	Can change cargo_ empregado	16	change_cargo_empregado
-- 63	Can delete cargo_ empregado	16	delete_cargo_empregado
-- 64	Can view cargo_ empregado	16	view_cargo_empregado
-- 65	Can add fp_nit	17	add_fp_nit
-- 66	Can change fp_nit	17	change_fp_nit
-- 67	Can delete fp_nit	17	delete_fp_nit
-- 68	Can view fp_nit	17	view_fp_nit
-- 69	Can add exec_ financeira	18	add_exec_financeira
-- 70	Can change exec_ financeira	18	change_exec_financeira
-- 71	Can delete exec_ financeira	18	delete_exec_financeira
-- 72	Can view exec_ financeira	18	view_exec_financeira
-- 73	Can add exec_ valores	19	add_exec_valores
-- 74	Can change exec_ valores	19	change_exec_valores
-- 75	Can delete exec_ valores	19	delete_exec_valores
-- 76	Can view exec_ valores	19	view_exec_valores
-- \.


-- --
-- -- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
-- 1	pbkdf2_sha256$720000$lNy073MR0IEj6RQ07izmf6$nuu89v/P/SlFZse6J6S6B2XOTGnL7pvF8gnergR1SFM=	2024-04-01 12:20:03.424918+00	t	matheus				t	t	2024-03-13 14:08:01.087002+00
-- \.


-- --
-- -- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: andamento; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.andamento (id, porcent_executada, data, atividade_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: atividade; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.atividade (id, nome, descricao, link_img, link_exec, peso, data_inicio, data_final, fp_nit_id, meta_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: cargo; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.cargo (id, nome, descricao) FROM stdin;
-- \.


-- --
-- -- Data for Name: cargo_empregado; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.cargo_empregado (id, data_inicio_cargo, data_final_cargo, cargo_id, empregado_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: contrato; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.contrato (id, data_contratacao, data_vencimento, cargo_empregado_atual_id, empregado_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: convenio; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.convenio (id, codigo, nome, descricao, data_inicio, data_final, orcamento) FROM stdin;
-- \.


-- --
-- -- Data for Name: convenio_empregado; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.convenio_empregado (id, atuacao_empregado, data_inicio_atuacao, data_final_atuacao, convenio_id, empregado_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: empregado; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.empregado (id, matricula_cracha, nome, cpf, email, data_nascimento, genero, telefone, graduacao) FROM stdin;
-- \.


-- --
-- -- Data for Name: evento; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.evento (id, nome, descricao, denominacao, participantes, categoria_participantes, data_inicio, data_final, convenio_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: exec_financeira; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.exec_financeira (id, orc_total, rep_recebidos, saldo_receber, redimento, total_realizado, total_empenhado, saldo_executar, data, convenio_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: exec_valores; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.exec_valores (id, desc_execute, aloc, custo, rubrica, data, convenio_id, meta) FROM stdin;
-- \.


-- --
-- -- Data for Name: fp_nit; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.fp_nit (id, nome, descricao, data_inicio, data_final, meta_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: meta; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.meta (id, nome, descricao, data_inicio, data_final, convenio_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
-- \.


-- --
-- -- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.django_content_type (id, app_label, model) FROM stdin;
-- 1	admin	logentry
-- 2	auth	permission
-- 3	auth	group
-- 4	auth	user
-- 5	contenttypes	contenttype
-- 6	sessions	session
-- 7	base	cargo
-- 8	base	convenio
-- 9	base	empregado
-- 10	base	contrato
-- 11	base	meta
-- 12	base	atividade
-- 13	base	evento
-- 14	base	convenio_empregado
-- 15	base	andamento
-- 16	base	cargo_empregado
-- 17	base	fp_nit
-- 18	base	exec_financeira
-- 19	base	exec_valores
-- \.


-- --
-- -- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.django_migrations (id, app, name, applied) FROM stdin;
-- 1	contenttypes	0001_initial	2024-03-11 19:45:44.947485+00
-- 2	auth	0001_initial	2024-03-11 19:45:45.035154+00
-- 3	admin	0001_initial	2024-03-11 19:45:45.058142+00
-- 4	admin	0002_logentry_remove_auto_add	2024-03-11 19:45:45.06455+00
-- 5	admin	0003_logentry_add_action_flag_choices	2024-03-11 19:45:45.071572+00
-- 6	contenttypes	0002_remove_content_type_name	2024-03-11 19:45:45.086115+00
-- 7	auth	0002_alter_permission_name_max_length	2024-03-11 19:45:45.095582+00
-- 8	auth	0003_alter_user_email_max_length	2024-03-11 19:45:45.118241+00
-- 9	auth	0004_alter_user_username_opts	2024-03-11 19:45:45.124516+00
-- 10	auth	0005_alter_user_last_login_null	2024-03-11 19:45:45.132248+00
-- 11	auth	0006_require_contenttypes_0002	2024-03-11 19:45:45.133869+00
-- 12	auth	0007_alter_validators_add_error_messages	2024-03-11 19:45:45.140733+00
-- 13	auth	0008_alter_user_username_max_length	2024-03-11 19:45:45.154663+00
-- 14	auth	0009_alter_user_last_name_max_length	2024-03-11 19:45:45.16126+00
-- 15	auth	0010_alter_group_name_max_length	2024-03-11 19:45:45.169552+00
-- 16	auth	0011_update_proxy_permissions	2024-03-11 19:45:45.175384+00
-- 17	auth	0012_alter_user_first_name_max_length	2024-03-11 19:45:45.183849+00
-- 18	base	0001_initial	2024-03-11 19:45:45.255191+00
-- 19	base	0002_remove_contrato_id_cargo_empregado_and_more	2024-03-11 19:45:45.289539+00
-- 20	base	0003_initial	2024-03-11 19:45:45.364318+00
-- 21	sessions	0001_initial	2024-03-11 19:45:45.378712+00
-- 22	base	0004_remove_contrato_id_cargo_empregado_and_more	2024-03-11 19:46:34.671961+00
-- 23	base	0005_initial	2024-03-11 19:47:35.294271+00
-- 24	base	0006_andamento_atividade_link_exec_atividade_link_img_and_more	2024-03-13 14:06:20.328042+00
-- 25	base	0007_delete_andamento_remove_cargo_empregado_cargo_and_more	2024-03-13 14:23:23.884727+00
-- 26	base	0008_initial	2024-03-13 14:23:35.966725+00
-- 27	base	0009_rename_data_final_cargo_empregado_data_final_cargo_and_more	2024-03-14 14:12:56.416475+00
-- 28	base	0010_remove_atividade_fp_nit_remove_atividade_meta_and_more	2024-03-22 19:07:55.564689+00
-- 29	base	0011_initial	2024-03-22 19:08:37.868384+00
-- 30	base	0012_alter_exec_valores_meta	2024-03-22 19:59:32.867224+00
-- \.


-- --
-- -- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
-- --

-- COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
-- 72dusvrnkw3sf1eou3hpg3c3acop13ih	.eJxVjEEOwiAQRe_C2pAOWEZcuu8ZyMxApWogKe3KeHdD0oVu_3vvv1Wgfcthb2kNS1RXBer0uzHJM5UO4oPKvWqpZVsX1l3RB216qjG9bof7d5Cp5V7bSIKO0ZB354jiRhIz8wzeCnhgSCMxEKQLCA4SB7IIRtg4i-is-nwBAAw4Fw:1rrGdv:u8NXJXZ__e6kQz_-_7ByR1JSEmCTx3Kh7DmHfJQewJA	2024-04-15 12:20:03.427612+00
-- \.


-- --
-- -- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


-- --
-- -- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


-- --
-- -- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


-- --
-- -- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


-- --
-- -- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


-- --
-- -- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: andamento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.andamento_id_seq', 1, false);


--
-- Name: atividade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.atividade_id_seq', 1, false);


--
-- Name: cargo_empregado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cargo_empregado_id_seq', 1, false);


--
-- Name: cargo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cargo_id_seq', 1, false);


--
-- Name: contrato_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contrato_id_seq', 1, false);


--
-- Name: convenio_empregado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.convenio_empregado_id_seq', 1, false);


--
-- Name: convenio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.convenio_id_seq', 1, false);


--
-- Name: empregado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empregado_id_seq', 1, false);


--
-- Name: evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evento_id_seq', 1, false);


--
-- Name: exec_financeira_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exec_financeira_id_seq', 1, false);


--
-- Name: exec_valores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exec_valores_id_seq', 1, false);


--
-- Name: fp_nit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fp_nit_id_seq', 1, false);


--
-- Name: meta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meta_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

-- SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


-- --
-- -- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


-- --
-- -- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
-- --

-- SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


-- --
-- -- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_group
--     ADD CONSTRAINT auth_group_name_key UNIQUE (name);


-- --
-- -- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_group_permissions
--     ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


-- --
-- -- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_group_permissions
--     ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


-- --
-- -- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_group
--     ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


-- --
-- -- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_permission
--     ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


-- --
-- -- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_permission
--     ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


-- --
-- -- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_groups
--     ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


-- --
-- -- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_groups
--     ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


-- --
-- -- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user
--     ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


-- --
-- -- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_user_permissions
--     ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


-- --
-- -- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_user_permissions
--     ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


-- --
-- -- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user
--     ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: andamento andamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.andamento
    ADD CONSTRAINT andamento_pkey PRIMARY KEY (id);


--
-- Name: atividade atividade_fp_nit_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.atividade
    ADD CONSTRAINT atividade_fp_nit_id_key UNIQUE (fp_nit_id);


--
-- Name: atividade atividade_meta_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.atividade
    ADD CONSTRAINT atividade_meta_id_key UNIQUE (meta_id);


--
-- Name: atividade atividade_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.atividade
    ADD CONSTRAINT atividade_pkey PRIMARY KEY (id);


--
-- Name: cargo_empregado cargo_empregado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cargo_empregado
    ADD CONSTRAINT cargo_empregado_pkey PRIMARY KEY (id);


--
-- Name: cargo cargo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cargo
    ADD CONSTRAINT cargo_pkey PRIMARY KEY (id);


--
-- Name: contrato contrato_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrato
    ADD CONSTRAINT contrato_pkey PRIMARY KEY (id);


--
-- Name: convenio_empregado convenio_empregado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.convenio_empregado
    ADD CONSTRAINT convenio_empregado_pkey PRIMARY KEY (id);


--
-- Name: convenio convenio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.convenio
    ADD CONSTRAINT convenio_pkey PRIMARY KEY (id);


--
-- Name: empregado empregado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empregado
    ADD CONSTRAINT empregado_pkey PRIMARY KEY (id);


--
-- Name: evento evento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evento
    ADD CONSTRAINT evento_pkey PRIMARY KEY (id);


--
-- Name: exec_financeira exec_financeira_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exec_financeira
    ADD CONSTRAINT exec_financeira_pkey PRIMARY KEY (id);


--
-- Name: exec_valores exec_valores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exec_valores
    ADD CONSTRAINT exec_valores_pkey PRIMARY KEY (id);


--
-- Name: fp_nit fp_nit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fp_nit
    ADD CONSTRAINT fp_nit_pkey PRIMARY KEY (id);


--
-- Name: meta meta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meta
    ADD CONSTRAINT meta_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

-- ALTER TABLE ONLY public.django_admin_log
--     ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


-- --
-- -- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.django_content_type
--     ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


-- --
-- -- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.django_content_type
--     ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


-- --
-- -- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.django_migrations
--     ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


-- --
-- -- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.django_session
--     ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


-- --
-- -- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- --
-- -- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


-- --
-- -- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


-- --
-- -- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- --
-- -- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


-- --
-- -- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


-- --
-- -- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


-- --
-- -- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


-- --
-- -- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
-- --

-- CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: andamento_atividade_id_05dcdc82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX andamento_atividade_id_05dcdc82 ON public.andamento USING btree (atividade_id);


--
-- Name: cargo_empregado_cargo_id_1c616630; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cargo_empregado_cargo_id_1c616630 ON public.cargo_empregado USING btree (cargo_id);


--
-- Name: cargo_empregado_empregado_id_da522171; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cargo_empregado_empregado_id_da522171 ON public.cargo_empregado USING btree (empregado_id);


--
-- Name: contrato_cargo_empregado_atual_id_c5aed21a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contrato_cargo_empregado_atual_id_c5aed21a ON public.contrato USING btree (cargo_empregado_atual_id);


--
-- Name: contrato_empregado_id_7a303ef7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contrato_empregado_id_7a303ef7 ON public.contrato USING btree (empregado_id);


--
-- Name: convenio_empregado_convenio_id_775795a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX convenio_empregado_convenio_id_775795a2 ON public.convenio_empregado USING btree (convenio_id);


--
-- Name: convenio_empregado_empregado_id_f447b36c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX convenio_empregado_empregado_id_f447b36c ON public.convenio_empregado USING btree (empregado_id);


--
-- Name: evento_convenio_id_d1f54cc6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX evento_convenio_id_d1f54cc6 ON public.evento USING btree (convenio_id);


--
-- Name: exec_financeira_convenio_id_63393404; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exec_financeira_convenio_id_63393404 ON public.exec_financeira USING btree (convenio_id);


--
-- Name: exec_valores_convenio_id_a6f6aeef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exec_valores_convenio_id_a6f6aeef ON public.exec_valores USING btree (convenio_id);


--
-- Name: fp_nit_meta_id_cea43dcb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fp_nit_meta_id_cea43dcb ON public.fp_nit USING btree (meta_id);


--
-- Name: meta_convenio_id_2a1abec7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX meta_convenio_id_2a1abec7 ON public.meta USING btree (convenio_id);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

-- CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- --
-- -- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_group_permissions
--     ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- -- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_group_permissions
--     ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- -- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_permission
--     ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- -- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_groups
--     ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- -- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_groups
--     ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- -- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_user_permissions
--     ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- -- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.auth_user_user_permissions
--     ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: andamento andamento_atividade_id_05dcdc82_fk_atividade_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.andamento
    ADD CONSTRAINT andamento_atividade_id_05dcdc82_fk_atividade_id FOREIGN KEY (atividade_id) REFERENCES public.atividade(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: atividade atividade_fp_nit_id_c0ff2d32_fk_fp_nit_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.atividade
    ADD CONSTRAINT atividade_fp_nit_id_c0ff2d32_fk_fp_nit_id FOREIGN KEY (fp_nit_id) REFERENCES public.fp_nit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: atividade atividade_meta_id_64a01567_fk_meta_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.atividade
    ADD CONSTRAINT atividade_meta_id_64a01567_fk_meta_id FOREIGN KEY (meta_id) REFERENCES public.meta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cargo_empregado cargo_empregado_cargo_id_1c616630_fk_cargo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cargo_empregado
    ADD CONSTRAINT cargo_empregado_cargo_id_1c616630_fk_cargo_id FOREIGN KEY (cargo_id) REFERENCES public.cargo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cargo_empregado cargo_empregado_empregado_id_da522171_fk_empregado_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cargo_empregado
    ADD CONSTRAINT cargo_empregado_empregado_id_da522171_fk_empregado_id FOREIGN KEY (empregado_id) REFERENCES public.empregado(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contrato contrato_cargo_empregado_atua_c5aed21a_fk_carg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrato
    ADD CONSTRAINT contrato_cargo_empregado_atua_c5aed21a_fk_carg FOREIGN KEY (cargo_empregado_atual_id) REFERENCES public.cargo_empregado(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contrato contrato_empregado_id_7a303ef7_fk_empregado_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrato
    ADD CONSTRAINT contrato_empregado_id_7a303ef7_fk_empregado_id FOREIGN KEY (empregado_id) REFERENCES public.empregado(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: convenio_empregado convenio_empreg_convenio_id_775795a2_fk_conv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.convenio_empregado
    ADD CONSTRAINT convenio_empreg_convenio_id_775795a2_fk_conv FOREIGN KEY (convenio_id) REFERENCES public.convenio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: convenio_empregado convenio_empreg_empregado_id_f447b36c_fk_empr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.convenio_empregado
    ADD CONSTRAINT convenio_empreg_empregado_id_f447b36c_fk_empr FOREIGN KEY (empregado_id) REFERENCES public.empregado(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: evento evento_convenio_id_d1f54cc6_fk_convenio_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evento
    ADD CONSTRAINT evento_convenio_id_d1f54cc6_fk_convenio_id FOREIGN KEY (convenio_id) REFERENCES public.convenio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exec_financeira exec_financeira_convenio_id_63393404_fk_convenio_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exec_financeira
    ADD CONSTRAINT exec_financeira_convenio_id_63393404_fk_convenio_id FOREIGN KEY (convenio_id) REFERENCES public.convenio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exec_valores exec_valores_convenio_id_a6f6aeef_fk_convenio_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exec_valores
    ADD CONSTRAINT exec_valores_convenio_id_a6f6aeef_fk_convenio_id FOREIGN KEY (convenio_id) REFERENCES public.convenio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: fp_nit fp_nit_meta_id_cea43dcb_fk_meta_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fp_nit
    ADD CONSTRAINT fp_nit_meta_id_cea43dcb_fk_meta_id FOREIGN KEY (meta_id) REFERENCES public.meta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: meta meta_convenio_id_2a1abec7_fk_convenio_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meta
    ADD CONSTRAINT meta_convenio_id_2a1abec7_fk_convenio_id FOREIGN KEY (convenio_id) REFERENCES public.convenio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

-- ALTER TABLE ONLY public.django_admin_log
--     ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- -- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
-- --

-- ALTER TABLE ONLY public.django_admin_log
--     ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- --
-- PostgreSQL database dump complete
--

