# Generated by Django 5.0.1 on 2024-03-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, null=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255, null=True)),
                ('graduacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuacao_empregado', models.CharField(max_length=255)),
                ('data_contratacao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('id_cargo_empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cargo')),
                ('id_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
                ('id_empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('codigo_convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('id_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.meta')),
            ],
        ),
    ]
