# Generated by Django 5.0.1 on 2024-03-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_remove_contrato_id_cargo_empregado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('orcamento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, null=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255, null=True)),
                ('graduacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio_Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuacao_empregado', models.CharField(max_length=255)),
                ('data_inicio_atuacao', models.DateField()),
                ('data_final_atuacao', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('cargo_empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cargo')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.meta')),
            ],
        ),
    ]
