# Generated by Django 5.0.1 on 2024-03-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_andamento_atividade_link_exec_atividade_link_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Andamento',
        ),
        migrations.RemoveField(
            model_name='cargo_empregado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='cargo_empregado',
            name='empregado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cargo_empregado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='empregado',
        ),
        migrations.RemoveField(
            model_name='convenio_empregado',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='convenio_empregado',
            name='empregado',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Cargo_Empregado',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Convenio_Empregado',
        ),
        migrations.DeleteModel(
            name='Empregado',
        ),
    ]
