# Generated by Django 5.0.1 on 2024-03-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_data_final_cargo_empregado_data_final_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='fp_nit',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='cargo_empregado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='cargo_empregado',
            name='empregado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cargo_empregado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='empregado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='convenio_empregado',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='convenio_empregado',
            name='empregado',
        ),
        migrations.RemoveField(
            model_name='fp_nit',
            name='meta',
        ),
        migrations.DeleteModel(
            name='Andamento',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Cargo_Empregado',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.DeleteModel(
            name='Convenio_Empregado',
        ),
        migrations.DeleteModel(
            name='Empregado',
        ),
        migrations.DeleteModel(
            name='Fp_nit',
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
