# Generated by Django 5.0.1 on 2024-03-22 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_remove_atividade_fp_nit_remove_atividade_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('link_img', models.CharField(max_length=4000, null=True)),
                ('link_exec', models.CharField(max_length=4000, null=True)),
                ('peso', models.IntegerField(choices=[(1, '1'), (3, '3'), (6, '6')], null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('orcamento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_cracha', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=2000)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, null=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255, null=True)),
                ('graduacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fp_nit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcent_executada', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data', models.DateField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_cargo', models.DateField()),
                ('data_final_cargo', models.DateField(null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cargo')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Convenio_Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuacao_empregado', models.CharField(max_length=255)),
                ('data_inicio_atuacao', models.DateField()),
                ('data_final_atuacao', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('cargo_empregado_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cargo_empregado')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empregado')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('denominacao', models.CharField(max_length=2000)),
                ('participantes', models.CharField(max_length=2000)),
                ('categoria_participantes', models.CharField(max_length=2000)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Exec_Financeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orc_total', models.FloatField(null=True)),
                ('rep_recebidos', models.FloatField(null=True)),
                ('saldo_receber', models.FloatField(null=True)),
                ('redimento', models.FloatField(null=True)),
                ('total_realizado', models.FloatField(null=True)),
                ('total_empenhado', models.FloatField(null=True)),
                ('saldo_executar', models.FloatField(null=True)),
                ('data', models.DateField(null=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='fp_nit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fp_nit'),
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
            ],
        ),
        migrations.AddField(
            model_name='fp_nit',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.meta'),
        ),
        migrations.CreateModel(
            name='Exec_Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_execute', models.TextField(null=True)),
                ('aloc', models.CharField(max_length=50, null=True)),
                ('custo', models.FloatField(null=True)),
                ('rubrica', models.CharField(max_length=255, null=True)),
                ('data', models.DateField(null=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.convenio')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.meta')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='meta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.meta'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('meta__isnull', False), ('fp_nit__isnull', True)), models.Q(('meta__isnull', True), ('fp_nit__isnull', False)), _connector='OR'), name='check_activity_fields'),
        ),
    ]
