# Generated by Django 5.0.1 on 2024-03-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exec_valores',
            name='meta',
            field=models.CharField(max_length=255),
        ),
    ]
