# Generated by Django 5.0.1 on 2024-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_exec_valores_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='link_exec',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='link_img',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
