# Generated by Django 5.0.1 on 2024-04-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_atividade_link_exec_alter_atividade_link_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='fp_nit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fp_nit'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.meta'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='peso',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (3, '3'), (6, '6')], null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo_empregado',
            name='data_final_cargo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='orc_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='redimento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='rep_recebidos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='saldo_executar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='saldo_receber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='total_empenhado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_financeira',
            name='total_realizado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_valores',
            name='aloc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exec_valores',
            name='custo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_valores',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_valores',
            name='desc_execute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exec_valores',
            name='rubrica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fp_nit',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
