# Generated by Django 5.0.1 on 2024-04-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_atividade_descricao_alter_atividade_fp_nit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andamento',
            options={'verbose_name_plural': 'Andamento'},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name_plural': 'Atividade'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name_plural': 'Cargo'},
        ),
        migrations.AlterModelOptions(
            name='cargo_empregado',
            options={'verbose_name_plural': 'Cargo_Empregado'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name_plural': 'Contrato'},
        ),
        migrations.AlterModelOptions(
            name='convenio',
            options={'verbose_name_plural': 'Convenio'},
        ),
        migrations.AlterModelOptions(
            name='convenio_empregado',
            options={'verbose_name_plural': 'Convenio_Empregado'},
        ),
        migrations.AlterModelOptions(
            name='empregado',
            options={'verbose_name_plural': 'Empregado'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name_plural': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='exec_financeira',
            options={'verbose_name_plural': 'Exec_Financeira'},
        ),
        migrations.AlterModelOptions(
            name='exec_valores',
            options={'verbose_name_plural': 'Exec_Valores'},
        ),
        migrations.AlterModelOptions(
            name='fp_nit',
            options={'verbose_name_plural': 'Fp_nit'},
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'verbose_name_plural': 'Meta'},
        ),
    ]
