# Generated by Django 5.0.1 on 2024-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_andamento_options_alter_atividade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria_participantes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='denominacao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
