# Generated by Django 5.0.1 on 2024-04-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_convenio_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='genero',
            field=models.CharField(choices=[('Homem', 'Homem'), ('Mulher', 'Mulher'), ('Outro', 'Outro')], max_length=255),
        ),
    ]
