# Generated by Django 5.0.1 on 2024-05-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_atividade_check_activity_fields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='cargo_empregado_atual',
            new_name='cargo_empregado',
        ),
    ]
