# Generated by Django 5.0.1 on 2024-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_cargo_empregado_atual_contrato_cargo_empregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='indicador',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
