# Generated by Django 5.0.1 on 2024-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_meta_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='indicador',
        ),
        migrations.AddField(
            model_name='atividade',
            name='indicador',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
