# Generated by Django 5.0.1 on 2024-06-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atvmetas',
            table='dashboards"."atv_metas',
        ),
    ]
