# Generated by Django 5.0.1 on 2024-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_alter_atvmetas_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndAtividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.CharField(blank=True, max_length=2000, null=True)),
                ('atividade', models.CharField(blank=True, max_length=2000, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link_img', models.CharField(blank=True, max_length=4000, null=True)),
                ('link_exec', models.CharField(blank=True, max_length=4000, null=True)),
                ('ult_atual_date', models.CharField(blank=True, max_length=50, null=True)),
                ('perc_and', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'dashboards"."and_atividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AndAtividadesNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fpname', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta', models.CharField(blank=True, max_length=2000, null=True)),
                ('atividade', models.CharField(blank=True, max_length=2000, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link_img', models.CharField(blank=True, max_length=4000, null=True)),
                ('link_exec', models.CharField(blank=True, max_length=4000, null=True)),
                ('ult_atual_date', models.CharField(blank=True, max_length=50, null=True)),
                ('perc_and', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."and_atividades_nit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtvIndicadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.CharField(blank=True, max_length=2000, null=True)),
                ('atividade', models.CharField(blank=True, max_length=2000, null=True)),
                ('indicador', models.CharField(blank=True, max_length=20000, null=True)),
                ('begin_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dashboards"."atv_indicadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtvMetasNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meta', models.CharField(blank=True, max_length=2000, null=True)),
                ('atividade', models.CharField(blank=True, max_length=2000, null=True)),
                ('begin_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."atv_metas_nit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(blank=True, max_length=2000, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('graduacao', models.CharField(blank=True, max_length=255, null=True)),
                ('atuacao', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('nascimento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_contratacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_venc_contrato', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dashboards"."employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeesNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('graduacao', models.CharField(blank=True, max_length=255, null=True)),
                ('atuacao_nit', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('nascimento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_contratacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_venc_contrato', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."employees_nit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(blank=True, max_length=2000, null=True)),
                ('den_event', models.CharField(blank=True, max_length=2000, null=True)),
                ('part_evento', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_evento', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_evento', models.CharField(blank=True, max_length=8000, null=True)),
                ('cat_evento', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'dashboards"."eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('den_event', models.CharField(blank=True, max_length=2000, null=True)),
                ('part_evento', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_evento', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_evento', models.CharField(blank=True, max_length=8000, null=True)),
                ('cat_evento', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."eventos_nit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExecFinanceira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(blank=True, max_length=2000, null=True)),
                ('orc_total', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_recebidos', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo_receber', models.CharField(blank=True, max_length=255, null=True)),
                ('rendimento', models.CharField(blank=True, max_length=255, null=True)),
                ('total_realizado', models.CharField(blank=True, max_length=255, null=True)),
                ('total_empenhado', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo_executar', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dashboards"."execfinanceira',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExecFinanceiraNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orc_total', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_recebidos', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo_receber', models.CharField(blank=True, max_length=255, null=True)),
                ('rendimento', models.CharField(blank=True, max_length=255, null=True)),
                ('total_realizado', models.CharField(blank=True, max_length=255, null=True)),
                ('total_empenhado', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo_executar', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."execfinanceira_nit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExecValores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(blank=True, max_length=2000, null=True)),
                ('desc_execute', models.CharField(blank=True, max_length=2000, null=True)),
                ('aloc', models.CharField(blank=True, max_length=50, null=True)),
                ('custo', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.CharField(blank=True, max_length=255, null=True)),
                ('rubrica', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dashboards"."execvalores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExecValoresNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convenio', models.CharField(blank=True, max_length=2000, null=True)),
                ('desc_execute', models.CharField(blank=True, max_length=2000, null=True)),
                ('aloc', models.CharField(blank=True, max_length=50, null=True)),
                ('custo', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.CharField(blank=True, max_length=255, null=True)),
                ('rubrica', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."execvalores_nit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FpsNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fpname', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta', models.CharField(blank=True, max_length=2000, null=True)),
                ('atividade', models.CharField(blank=True, max_length=2000, null=True)),
                ('begin_date', models.CharField(blank=True, max_length=50, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."fps_nit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersNit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dash_nit"."users_nit',
                'managed': False,
            },
        ),
    ]
